name: Commit Tests
on:
  push:
  workflow_dispatch:

jobs:
  run-checks:
    name: run-checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ci
    steps:
      - uses: actions/checkout@v3
      - name: Run checks from container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: just check
